# This is a sample configuration file for a production environment. Use production override files for customization.

services:
  pygamecommunitybot:
    image: pygamecommunitybot:latest
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    stop_signal: SIGINT
    environment:
      - TOKEN=${TOKEN:-} # A string representation of a discord bot token
      - CONFIG_PY=${CONFIG_PY:-} # A string representation of a config.py file
      - LOCALCONFIG_PY=${LOCALCONFIG_PY:-} # A string representation of a localconfig.py file
    volumes:
      - pcbot-env-volume:/app/env/
      - pcbot-logs-volume:/app/logs/
      - pcbot-db-volume:/app/db/
    tty: true
