# This is a sample configuration file for a production environment. Use production override files for customization.

services:
  pygamecommunitybot:
    image: pygamecommunitybot:latest
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    stop_signal: SIGINT
    volumes:
      # Mount environment and config files directory
      # to the service as a volume
      - ${ENV_VOLUME}:/app/env/
    tty: true
