# This is a sample configuration file for a production environment. Use production override files for customization.

services:
  pygamecommunitybot:
    build:
      context: .
      dockerfile: Dockerfile
    image: pcbot-main:latest
    container_name: pcbot-main
    restart: unless-stopped
    stop_signal: SIGINT
    environment:
      - TOKEN=${TOKEN:-} # A string representation of a discord bot token
      - CONFIG_PY=${CONFIG_PY:-} # A string representation of a config.py file
      - LOCALCONFIG_PY=${LOCALCONFIG_PY:-} # A string representation of a localconfig.py file
    volumes:
      - pcbot-env-volume:/app/env/
      - pcbot-logs-volume:/app/logs/
      - pcbot-db-volume:/app/db/
    tty: true

volumes:
  pcbot-env-volume:
  pcbot-logs-volume:
  pcbot-db-volume:
