services:
  pygamecommunitybot:
    image: pygamecommunitybot:latest
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
      no_cache: true
    tty: true
    volumes:
      - /mnt/blockstorage:/mnt/blockstorage
